id: I04A87A0C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T14:44:02+00:00'
last_modified: '2022-06-08T14:08:56.711620+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30090
  title: ཇོ་ནང་ཆོས་འབྱུང་ཟླ་བའི་སྒྲོན་མེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E587:
      image_group_id: I5808
      title: ''
      total_pages: 620
      order: 1
      base_file: E587.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
