id: P010513
initial_creation_type: ocr
source_metadata:
  id: bdr:W30090
  title: ཇོ་ནང་ཆོས་འབྱུང་ཟླ་བའི་སྒྲོན་མེ
  author: ''
  volumes:
    aab0c0384aba42b095720626b0383304:
      image_group_id: I5808
      title: ''
      volume_number: 1
      total_pages: 620
      base_file: v001.txt
